  steps:
  # Step to build your container image
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/nyyu-391719/frontend-nyyu-io-prod', '.']
  
  # Step to push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/nyyu-391719/frontend-nyyu-io-prod']
  
  # Step to deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'frontend-nyyu-io-prod'
      - '--image=gcr.io/nyyu-391719/frontend-nyyu-io-prod'
      - '--region=europe-west2'
      - '--platform=managed'
      - '--allow-unauthenticated'
  images: 
    - 'gcr.io/nyyu-391719/frontend-nyyu-io-prod'
