export const ROUTES = {
    signIn: "/app/signin/",
    signUp: "/app/signup/",
    selectFigure: "/app/select-figure/",
    verifyFailed: "/app/verify-failed/",
    verifyEmail: "/app/verify-email/",
    verifyCompany: "/app/verify-company/",
    verifyId: "/app/verify-id/",
    profile: "/app/profile/",
    changePassword: "/app/change-password/",
    forgotPassword: "/app/forgot-password/",
    payment: "/app/payment/",
    auction: "/app/auction/",
    home: "/",
    faq: "/app/support/",
    wallet: "/app/wallet/",
    admin: "/admin",
    presale_auction: "/pre-sale/auction",
    presale_home: "/pre-sale/home",
}
