export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

export const CREATE_AVATAR_COMPONENT = "CREATE_AVATAR_COMPONENT";
export const UPDATE_AVATAR_COMPONENT = "UPDATE_AVATAR_COMPONENT";
export const DELETE_AVATAR_COMPONENT = 'DELETE_AVATAR_COMPONENT';
export const FETCH_AVATAR_COMPONENTS = "FETCH_AVATAR_COMPONENTS";

export const FETCH_AVATARS = "FETCH_AVATARS";
export const CREATE_NEW_AVATAR = "CREATE_NEW_AVATAR";

export const BID_PLACE = "BID_PLACE";

export const GET_USER_TIERS = "GET_USER_TIERS";
export const CREATE_USER_TIER = "CREATE_USER_TIER";
export const UPDATE_USER_TIER = "UPDATE_USER_TIER";
export const DELETE_USER_TIER = "DELETE_USER_TIER";

export const SET_CURRENCY = "SET_CURRENCY";
export const SET_CURRENT_ROUND_ID = "SET_CURRENT_ROUND_ID";
export const SET_PRESALE_ORDER_ID = 'SET_PRESALE_ORDER_ID';

export const PAGINATION_SET_PAGE = "PAGINATION_SET_PAGE";
export const PAGINATION_SET_LIMIT = "PAGINATION_SET_LIMIT";
export const PAGINATION_SET_TOTAL = "PAGINATION_SET_TOTAL";

export const FETCH_DATA = "FETCH_DATA";
export const UPDATE_DATUM = "UPDATE_DATUM";
export const DELETE_DATUM = "DELETE_DATUM";

export const FETCH_KYC_SETTINGS = "FETCH_KYC_SETTINGS";
export const UPDATE_KYC_SETTING = "UPDATE_KYC_SETTING";

export const FETCH_TASK_SETTING = "FETCH_TASK_SETTING";

export const SET_ALL_FEES = "SET_ALL_FEES";
export const SET_TEMP_DATA = 'SET_TEMP_DATA';

export const CREATE_NOTIFICATION_ROUTE = "CREATE_NOTIFICATION_ROUTE";
export const DISABLE_NOTIFICATION_ROUTE = "DISABLE_NOTIFICATION_ROUTE";
export const TIER_TAB = 'TIER_TAB';

export const FETCH_CURRENCY_RATES = 'FETCH_CURRENCY_RATES';

export const UPDATE_USER_ROLE = 'UPDATE_USER_ROLE';

export const FETCH_FAVOR_ASSETS = 'FETCH_FAVOR_ASSETS';
export const UPDATE_FAVOR_ASSETS = 'UPDATE_FAVOR_ASSETS';

export const FILL_USER_TIERS = 'FILL_USER_TIERS';