# .github/workflows/mirror.yml
name: Mirror to Public Repo

on:
  push:
    branches:
      - production  # or your default branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # full history

      - name: Remove sensitive files
        run: |
          rm -f .env
          rm -rf secret-folder-if-any

      - name: Debug token presence
        run: |
          echo "Token length: ${#PUBLIC_REPO_TOKEN}"
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}

      - name: Push to public repo
        env:
          PAT: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git config --global user.email "info@orb.group"
          git config --global user.name "golsharifi"
          git remote add public https://x-access-token:${PAT}@github.com/optitor/public.nyyu.io.git
          git push --force public HEAD:main
